// Generated by CoffeeScript 1.7.1
(function() {
  Todos.Router.map(function() {
    return this.resource('todos', {
      path: '/'
    }, function() {
      this.route('index', {
        path: '/'
      });
      return this.route('active');
    });
  });

  Todos.TodosRoute = Ember.Route.extend({
    model: function() {
      return this.store.find('todo');
    }
  });

  Todos.TodosActiveRoute = Ember.Route.extend({
    model: function() {
      return this.store.filter('todo', function(todo) {
        return !todo.get('isCompleted');
      });
    },
    renderTemplate: function(controller) {
      return this.render('todos/index', {
        controller: controller
      });
    }
  });

  Todos.TodosIndexRoute = Ember.Route.extend({
    model: function() {
      return this.modelFor('todos');
    }
  });

}).call(this);
