// Generated by CoffeeScript 1.7.1
(function() {
  Todos.EditTodoView = Ember.TextField.extend({
    didInsertElement: function() {
      return this.$().focus();
    }
  });

  Ember.Handlebars.helper('edit-todo', Todos.EditTodoView);

}).call(this);
