// Generated by CoffeeScript 1.7.1
(function() {
  Todos.TodoController = Ember.ObjectController.extend({
    isCompleted: (function(key, value) {
      var model;
      model = this.get('model');
      if (value === void 0) {
        return model.get('isCompleted');
      } else {
        model.set('isCompleted', value);
        model.save();
        return value;
      }
    }).property('model.isCompleted')
  });

}).call(this);
